/* Body file for function Buzzer
 * Generated by TASTE on 2021-11-18 15:33:41
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Fizzing
 * Required interfaces :
 * User-defined properties for this function:
 *   |_ TASTE::Is_Component_Type = false
 * Timers              :
 */

#include "buzzer.h"
#include <stdio.h>
#include <Hal.h>

void buzzer_startup(void)
{
}

void buzzer_PI_Fizzing(const asn1SccMyInteger* IN_fuzzargument)
{
    buzzer_RI_Increment(IN_fuzzargument);
}

void buzzer_PI_Result(const asn1SccMyInteger* IN_resultargument)
{
    buzzer_RI_Buzzing(IN_resultargument);
}
