
/* Header file for function Buzzer in C language
 * Generated by TASTE on 2021-11-19 11:42:12
 * Context Parameters present : NO
 * Provided interfaces : Fizzing, Result
 * Required interfaces : Buzzing, Increment
 * User-defined properties for this function:
  *  |_ TASTE::Is_Component_Type = false
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void buzzer_startup(void);

/* Provided interfaces */
void buzzer_PI_Fizzing( const asn1SccMyInteger * );
void buzzer_PI_Result( const asn1SccMyInteger * );

/* Required interfaces */
extern void buzzer_RI_Buzzing( const asn1SccMyInteger * );
extern void buzzer_RI_Increment( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
