/* Body file for function Incrementer
 * Generated by TASTE on 2021-11-18 16:57:33
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Increment
 * Required interfaces :
 * User-defined properties for this function:
 *   |_ TASTE::Is_Component_Type = false
 * Timers              :
 */
#include "incrementer.h"

#include <stdio.h>
#include <Hal.h>

void incrementer_startup(void)
{
}

void incrementer_PI_Increment(const asn1SccMyInteger* IN_incrementarg)
{
    static uint64_t result = 0;
    result = (*IN_incrementarg) + 1;

    incrementer_RI_Result(&result);
}


