
/* Header file for function Incrementer in C language
 * Generated by TASTE on 2021-11-19 11:42:13
 * Context Parameters present : NO
 * Provided interfaces : Increment
 * Required interfaces : Result
 * User-defined properties for this function:
  *  |_ TASTE::Is_Component_Type = false
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void incrementer_startup(void);

/* Provided interfaces */
void incrementer_PI_Increment( const asn1SccMyInteger * );

/* Required interfaces */
extern void incrementer_RI_Result( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
