
/* Header file for function Fuzzer in C language
 * Generated by TASTE on 2021-11-19 11:38:36
 * Context Parameters present : NO
 * Provided interfaces : Buzzing, PleaseFizzBuzz
 * Required interfaces : Fuzzing
 * User-defined properties for this function:
  *  |_ TASTE::Is_Component_Type = false
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void fuzzer_startup(void);

/* Provided interfaces */
void fuzzer_PI_Buzzing( const asn1SccMyInteger * );
void fuzzer_PI_PleaseFizzBuzz( void );

/* Required interfaces */
extern void fuzzer_RI_Fuzzing( const asn1SccMyInteger * );


#ifdef __cplusplus
}
#endif
