/* Body file for function fizzer
 * Generated by TASTE on 2021-11-18 14:37:21
 * You can edit this file, it will not be overwritten
 * Provided interfaces : PleasefizzBuzz
 * Required interfaces :
 * User-defined properties for this function:
 *   |_ TASTE::Is_Component_Type = false
 * Timers              :
 */

#include "fizzer.h"
#include <Hal.h>
#include <stdint.h>
#include <stdio.h>

static uint64_t value;

void fizzer_startup(void)
{
    value = 0;
}

void fizzer_PI_PleaseFizzBuzz(void)
{
    fizzer_RI_Fizzing(&value);
}

void fizzer_PI_Buzzing(const asn1SccMyInteger* IN_buzzargument)
{
    value = *IN_buzzargument;

    char message[64] = {0};
    if(value % 15 == 0)
    {
        snprintf(message, 64, "FizzBuzz\r\n");
    }
    else if (value % 3 == 0)
    {
        snprintf(message, 64, "Fizz\r\n");
    }
    else if (value % 5 == 0)
    {
        snprintf(message, 64, "Buzz\r\n");
    }
    else
    {
        snprintf(message, 64, "%d\r\n", (int)value);
    }

    Hal_console_usart_write(message, 64);
}
