
/* Header file for function Clock in C language
 * Generated by TASTE on 2021-11-19 11:42:13
 * Context Parameters present : NO
 * Provided interfaces : ClkInterface
 * Required interfaces : PleaseFizzBuzz
 * User-defined properties for this function:
  *  |_ TASTE::Is_Component_Type = false
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void clock_startup(void);

/* Provided interfaces */
void clock_PI_ClkInterface( void );

/* Required interfaces */
extern void clock_RI_PleaseFizzBuzz( void );


#ifdef __cplusplus
}
#endif
