/* Body file for function Clock
 * Generated by TASTE on 2021-11-18 10:40:19
 * You can edit this file, it will not be overwritten
 * Provided interfaces :
 * Required interfaces : ClkInterface
 * User-defined properties for this function:
 *   |_ TASTE::Is_Component_Type = false
 * Timers              :
 */

#include "clock.h"
#include <Hal.h>

void clock_startup(void)
{
    Hal_console_usart_init();
}

void clock_PI_ClkInterface(void)
{
    clock_RI_PleaseFizzBuzz();
}
